//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.26 at 11:24:36 AM PST 
//


package ihe.iti.csd._2013;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CSD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CSD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="organizationDirectory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="organization" type="{urn:ihe:iti:csd:2013}organization" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="serviceDirectory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="service" type="{urn:ihe:iti:csd:2013}service" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="facilityDirectory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="facility" type="{urn:ihe:iti:csd:2013}facility" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="providerDirectory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="provider" type="{urn:ihe:iti:csd:2013}provider" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CSD", propOrder = {
    "organizationDirectory",
    "serviceDirectory",
    "facilityDirectory",
    "providerDirectory"
})
public class CSD {

    @XmlElement(required = true)
    protected CSD.OrganizationDirectory organizationDirectory;
    @XmlElement(required = true)
    protected CSD.ServiceDirectory serviceDirectory;
    @XmlElement(required = true)
    protected CSD.FacilityDirectory facilityDirectory;
    @XmlElement(required = true)
    protected CSD.ProviderDirectory providerDirectory;

    /**
     * Gets the value of the organizationDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link CSD.OrganizationDirectory }
     *     
     */
    public CSD.OrganizationDirectory getOrganizationDirectory() {
        return organizationDirectory;
    }

    /**
     * Sets the value of the organizationDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSD.OrganizationDirectory }
     *     
     */
    public void setOrganizationDirectory(CSD.OrganizationDirectory value) {
        this.organizationDirectory = value;
    }

    /**
     * Gets the value of the serviceDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link CSD.ServiceDirectory }
     *     
     */
    public CSD.ServiceDirectory getServiceDirectory() {
        return serviceDirectory;
    }

    /**
     * Sets the value of the serviceDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSD.ServiceDirectory }
     *     
     */
    public void setServiceDirectory(CSD.ServiceDirectory value) {
        this.serviceDirectory = value;
    }

    /**
     * Gets the value of the facilityDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link CSD.FacilityDirectory }
     *     
     */
    public CSD.FacilityDirectory getFacilityDirectory() {
        return facilityDirectory;
    }

    /**
     * Sets the value of the facilityDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSD.FacilityDirectory }
     *     
     */
    public void setFacilityDirectory(CSD.FacilityDirectory value) {
        this.facilityDirectory = value;
    }

    /**
     * Gets the value of the providerDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link CSD.ProviderDirectory }
     *     
     */
    public CSD.ProviderDirectory getProviderDirectory() {
        return providerDirectory;
    }

    /**
     * Sets the value of the providerDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CSD.ProviderDirectory }
     *     
     */
    public void setProviderDirectory(CSD.ProviderDirectory value) {
        this.providerDirectory = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="facility" type="{urn:ihe:iti:csd:2013}facility" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "facility"
    })
    public static class FacilityDirectory {

        protected List<Facility> facility;

        /**
         * Gets the value of the facility property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the facility property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFacility().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Facility }
         * 
         * 
         */
        public List<Facility> getFacility() {
            if (facility == null) {
                facility = new ArrayList<Facility>();
            }
            return this.facility;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="organization" type="{urn:ihe:iti:csd:2013}organization" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organization"
    })
    public static class OrganizationDirectory {

        protected List<Organization> organization;

        /**
         * Gets the value of the organization property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the organization property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrganization().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Organization }
         * 
         * 
         */
        public List<Organization> getOrganization() {
            if (organization == null) {
                organization = new ArrayList<Organization>();
            }
            return this.organization;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="provider" type="{urn:ihe:iti:csd:2013}provider" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "provider"
    })
    public static class ProviderDirectory {

        protected List<Provider> provider;

        /**
         * Gets the value of the provider property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the provider property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProvider().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Provider }
         * 
         * 
         */
        public List<Provider> getProvider() {
            if (provider == null) {
                provider = new ArrayList<Provider>();
            }
            return this.provider;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="service" type="{urn:ihe:iti:csd:2013}service" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "service"
    })
    public static class ServiceDirectory {

        protected List<Service> service;

        /**
         * Gets the value of the service property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the service property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getService().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Service }
         * 
         * 
         */
        public List<Service> getService() {
            if (service == null) {
                service = new ArrayList<Service>();
            }
            return this.service;
        }

    }

}
