//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.26 at 11:24:36 AM PST 
//


package ihe.iti.csd._2013;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ihe.iti.csd._2013 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CSD_QNAME = new QName("urn:ihe:iti:csd:2013", "CSD");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ihe.iti.csd._2013
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CareServicesRequest }
     * 
     */
    public CareServicesRequest createCareServicesRequest() {
        return new CareServicesRequest();
    }

    /**
     * Create an instance of {@link CareServicesResponse }
     * 
     */
    public CareServicesResponse createCareServicesResponse() {
        return new CareServicesResponse();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Name }
     * 
     */
    public ihe.iti.csd._2013.Name createName() {
        return new ihe.iti.csd._2013.Name();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Facility }
     * 
     */
    public ihe.iti.csd._2013.Facility createFacility() {
        return new ihe.iti.csd._2013.Facility();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Facility.Organizations }
     * 
     */
    public ihe.iti.csd._2013.Facility.Organizations createFacilityOrganizations() {
        return new ihe.iti.csd._2013.Facility.Organizations();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Facility.Organizations.Organization }
     * 
     */
    public ihe.iti.csd._2013.Facility.Organizations.Organization createFacilityOrganizationsOrganization() {
        return new ihe.iti.csd._2013.Facility.Organizations.Organization();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Organization }
     * 
     */
    public ihe.iti.csd._2013.Organization createOrganization() {
        return new ihe.iti.csd._2013.Organization();
    }

    /**
     * Create an instance of {@link Provider }
     * 
     */
    public Provider createProvider() {
        return new Provider();
    }

    /**
     * Create an instance of {@link Provider.Facilities }
     * 
     */
    public Provider.Facilities createProviderFacilities() {
        return new Provider.Facilities();
    }

    /**
     * Create an instance of {@link Provider.Facilities.Facility }
     * 
     */
    public Provider.Facilities.Facility createProviderFacilitiesFacility() {
        return new Provider.Facilities.Facility();
    }

    /**
     * Create an instance of {@link Provider.Organizations }
     * 
     */
    public Provider.Organizations createProviderOrganizations() {
        return new Provider.Organizations();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link CSD }
     * 
     */
    public CSD createCSD() {
        return new CSD();
    }

    /**
     * Create an instance of {@link CareServicesRequest.Expression }
     * 
     */
    public CareServicesRequest.Expression createCareServicesRequestExpression() {
        return new CareServicesRequest.Expression();
    }

    /**
     * Create an instance of {@link CareServicesRequest.Function }
     * 
     */
    public CareServicesRequest.Function createCareServicesRequestFunction() {
        return new CareServicesRequest.Function();
    }

    /**
     * Create an instance of {@link GetModificationsResponse }
     * 
     */
    public GetModificationsResponse createGetModificationsResponse() {
        return new GetModificationsResponse();
    }

    /**
     * Create an instance of {@link CareServicesResponse.Error }
     * 
     */
    public CareServicesResponse.Error createCareServicesResponseError() {
        return new CareServicesResponse.Error();
    }

    /**
     * Create an instance of {@link GetModificationsRequest }
     * 
     */
    public GetModificationsRequest createGetModificationsRequest() {
        return new GetModificationsRequest();
    }

    /**
     * Create an instance of {@link Codedtype }
     * 
     */
    public Codedtype createCodedtype() {
        return new Codedtype();
    }

    /**
     * Create an instance of {@link UniqueID }
     * 
     */
    public UniqueID createUniqueID() {
        return new UniqueID();
    }

    /**
     * Create an instance of {@link Credential }
     * 
     */
    public Credential createCredential() {
        return new Credential();
    }

    /**
     * Create an instance of {@link Geocode }
     * 
     */
    public Geocode createGeocode() {
        return new Geocode();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Service }
     * 
     */
    public ihe.iti.csd._2013.Service createService() {
        return new ihe.iti.csd._2013.Service();
    }

    /**
     * Create an instance of {@link OperatingHours }
     * 
     */
    public OperatingHours createOperatingHours() {
        return new OperatingHours();
    }

    /**
     * Create an instance of {@link ContactPoint }
     * 
     */
    public ContactPoint createContactPoint() {
        return new ContactPoint();
    }

    /**
     * Create an instance of {@link OtherID }
     * 
     */
    public OtherID createOtherID() {
        return new OtherID();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Name.CommonName }
     * 
     */
    public ihe.iti.csd._2013.Name.CommonName createNameCommonName() {
        return new ihe.iti.csd._2013.Name.CommonName();
    }

    /**
     * Create an instance of {@link Address.AddressLine }
     * 
     */
    public Address.AddressLine createAddressAddressLine() {
        return new Address.AddressLine();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Facility.OtherName }
     * 
     */
    public ihe.iti.csd._2013.Facility.OtherName createFacilityOtherName() {
        return new ihe.iti.csd._2013.Facility.OtherName();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Facility.Contact }
     * 
     */
    public ihe.iti.csd._2013.Facility.Contact createFacilityContact() {
        return new ihe.iti.csd._2013.Facility.Contact();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Facility.Organizations.Organization.Service }
     * 
     */
    public ihe.iti.csd._2013.Facility.Organizations.Organization.Service createFacilityOrganizationsOrganizationService() {
        return new ihe.iti.csd._2013.Facility.Organizations.Organization.Service();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Organization.OtherName }
     * 
     */
    public ihe.iti.csd._2013.Organization.OtherName createOrganizationOtherName() {
        return new ihe.iti.csd._2013.Organization.OtherName();
    }

    /**
     * Create an instance of {@link ihe.iti.csd._2013.Organization.Contact }
     * 
     */
    public ihe.iti.csd._2013.Organization.Contact createOrganizationContact() {
        return new ihe.iti.csd._2013.Organization.Contact();
    }

    /**
     * Create an instance of {@link Provider.Facilities.Facility.Service }
     * 
     */
    public Provider.Facilities.Facility.Service createProviderFacilitiesFacilityService() {
        return new Provider.Facilities.Facility.Service();
    }

    /**
     * Create an instance of {@link Provider.Organizations.Organization }
     * 
     */
    public Provider.Organizations.Organization createProviderOrganizationsOrganization() {
        return new Provider.Organizations.Organization();
    }

    /**
     * Create an instance of {@link Person.Name }
     * 
     */
    public Person.Name createPersonName() {
        return new Person.Name();
    }

    /**
     * Create an instance of {@link CSD.OrganizationDirectory }
     * 
     */
    public CSD.OrganizationDirectory createCSDOrganizationDirectory() {
        return new CSD.OrganizationDirectory();
    }

    /**
     * Create an instance of {@link CSD.ServiceDirectory }
     * 
     */
    public CSD.ServiceDirectory createCSDServiceDirectory() {
        return new CSD.ServiceDirectory();
    }

    /**
     * Create an instance of {@link CSD.FacilityDirectory }
     * 
     */
    public CSD.FacilityDirectory createCSDFacilityDirectory() {
        return new CSD.FacilityDirectory();
    }

    /**
     * Create an instance of {@link CSD.ProviderDirectory }
     * 
     */
    public CSD.ProviderDirectory createCSDProviderDirectory() {
        return new CSD.ProviderDirectory();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CSD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ihe:iti:csd:2013", name = "CSD")
    public JAXBElement<CSD> createCSD(CSD value) {
        return new JAXBElement<CSD>(_CSD_QNAME, CSD.class, null, value);
    }

}
