//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.26 at 11:24:36 AM PST 
//


package ihe.iti.csd._2013;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for operatingHours complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="operatingHours">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="openFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="dayOfTheWeek" type="{http://www.w3.org/2001/XMLSchema}integer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="beginningHour" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="endingHour" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="beginEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="endEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operatingHours", propOrder = {
    "openFlag",
    "dayOfTheWeek",
    "beginningHour",
    "endingHour",
    "beginEffectiveDate",
    "endEffectiveDate"
})
public class OperatingHours {

    protected boolean openFlag;
    protected List<BigInteger> dayOfTheWeek;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar beginningHour;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar endingHour;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar beginEffectiveDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endEffectiveDate;

    /**
     * Gets the value of the openFlag property.
     * 
     */
    public boolean isOpenFlag() {
        return openFlag;
    }

    /**
     * Sets the value of the openFlag property.
     * 
     */
    public void setOpenFlag(boolean value) {
        this.openFlag = value;
    }

    /**
     * Gets the value of the dayOfTheWeek property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dayOfTheWeek property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDayOfTheWeek().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigInteger }
     * 
     * 
     */
    public List<BigInteger> getDayOfTheWeek() {
        if (dayOfTheWeek == null) {
            dayOfTheWeek = new ArrayList<BigInteger>();
        }
        return this.dayOfTheWeek;
    }

    /**
     * Gets the value of the beginningHour property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBeginningHour() {
        return beginningHour;
    }

    /**
     * Sets the value of the beginningHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBeginningHour(XMLGregorianCalendar value) {
        this.beginningHour = value;
    }

    /**
     * Gets the value of the endingHour property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndingHour() {
        return endingHour;
    }

    /**
     * Sets the value of the endingHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndingHour(XMLGregorianCalendar value) {
        this.endingHour = value;
    }

    /**
     * Gets the value of the beginEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBeginEffectiveDate() {
        return beginEffectiveDate;
    }

    /**
     * Sets the value of the beginEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBeginEffectiveDate(XMLGregorianCalendar value) {
        this.beginEffectiveDate = value;
    }

    /**
     * Gets the value of the endEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndEffectiveDate() {
        return endEffectiveDate;
    }

    /**
     * Sets the value of the endEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndEffectiveDate(XMLGregorianCalendar value) {
        this.endEffectiveDate = value;
    }

}
