//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.26 at 11:24:36 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ihe:iti:csd:2013", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ihe.iti.csd._2013;
